"""Islas, comarcas y excepciones de nombres.

Extraído literalmente de FICHAS_MUNICIPALES.ipynb (celda 3, Pedro Delgado).
Si cambian ahí, hay que regenerar este fichero.
"""

ISLAS = {
    "Lanzarote": ["Arrecife", "Haría", "San Bartolomé", "Teguise", "Tías", "Tinajo", "Yaiza"],
    "Fuerteventura": ["Antigua", "Betancuria", "La Oliva", "Pájara", "Puerto del Rosario", "Tuineje"],
    "Gran Canaria": ["Agaete", "Arucas", "Las Palmas de Gran Canaria", "Santa Brígida", "Telde",
                     "Firgas", "Teror", "Valsequillo de Gran Canaria", "Valleseco", "Vega de San Mateo",
                     "Gáldar", "Moya", "Santa María de Guía de Gran Canaria", "Artenara",
                     "La Aldea de San Nicolás", "Tejeda", "Mogán", "San Bartolomé de Tirajana",
                     "Agüimes", "Ingenio", "Santa Lucía de Tirajana"],
    "Tenerife": ["San Cristóbal de La Laguna", "El Rosario", "Santa Cruz de Tenerife", "Tegueste",
                 "La Matanza de Acentejo", "Santa Úrsula", "El Sauzal", "Tacoronte",
                 "La Victoria de Acentejo", "Buenavista del Norte", "Garachico", "Los Silos",
                 "El Tanque", "La Guancha", "Icod de los Vinos", "San Juan de la Rambla",
                 "La Orotava", "Puerto de la Cruz", "Los Realejos", "Arico", "Fasnia",
                 "Granadilla de Abona", "San Miguel de Abona", "Vilaflor de Chasna", "Adeje",
                 "Arona", "Guía de Isora", "Santiago del Teide", "Arafo", "Candelaria", "Güímar"],
    "La Gomera": ["Agulo", "Hermigua", "Vallehermoso", "Alajeró", "San Sebastián de La Gomera",
                  "Valle Gran Rey"],
    "La Palma": ["Breña Alta", "Breña Baja", "Santa Cruz de La Palma", "Villa de Mazo", "Barlovento",
                 "Puntallana", "San Andrés y Sauces", "Garafía", "Puntagorda", "Tijarafe",
                 "Fuencaliente de La Palma", "Los Llanos de Aridane", "El Paso", "Tazacorte"],
    "El Hierro": ["Frontera", "Valverde", "El Pinar de El Hierro"],
}
COMARCAS = {
    "Lanzarote - Este": ["Arrecife", "San Bartolomé", "Tías"],
    "Lanzarote - Norte": ["Haría", "Teguise"],
    "Lanzarote - Suroeste": ["Tinajo", "Yaiza"],
    "Fuerteventura - Centro": ["Antigua", "Betancuria"],
    "Fuerteventura - Norte": ["La Oliva", "Puerto del Rosario"],
    "Fuerteventura - Sur": ["Pájara", "Tuineje"],
    "Gran Canaria - Área Metropolitana": ["Arucas", "Las Palmas de Gran Canaria",
                                          "Santa Brígida", "Telde"],
    "Gran Canaria - Centro Norte": ["Firgas", "Teror", "Valsequillo de Gran Canaria",
                                    "Valleseco", "Vega de San Mateo"],
    "Gran Canaria - Noroeste": ["Agaete", "Gáldar", "Moya",
                                "Santa María de Guía de Gran Canaria"],
    "Gran Canaria - Oeste": ["Artenara", "La Aldea de San Nicolás", "Tejeda"],
    "Gran Canaria - Suroeste": ["Mogán", "San Bartolomé de Tirajana"],
    "Gran Canaria - Sureste": ["Agüimes", "Ingenio", "Santa Lucía de Tirajana"],
    "Tenerife - Área Metropolitana": ["San Cristóbal de La Laguna", "El Rosario",
                                      "Santa Cruz de Tenerife", "Tegueste"],
    "Tenerife - Acentejo": ["La Matanza de Acentejo", "Santa Úrsula", "El Sauzal",
                            "Tacoronte", "La Victoria de Acentejo"],
    "Tenerife - Daute": ["Buenavista del Norte", "Garachico", "Los Silos", "El Tanque"],
    "Tenerife - Icod": ["La Guancha", "Icod de los Vinos", "San Juan de la Rambla"],
    "Tenerife - Valle de La Orotava": ["La Orotava", "Puerto de la Cruz", "Los Realejos"],
    "Tenerife - Abona": ["Arico", "Fasnia", "Granadilla de Abona",
                         "San Miguel de Abona", "Vilaflor de Chasna"],
    "Tenerife - Suroeste": ["Adeje", "Arona", "Guía de Isora", "Santiago del Teide"],
    "Tenerife - Valle de Güímar": ["Arafo", "Candelaria", "Güímar"],
    "La Gomera - Norte": ["Agulo", "Hermigua", "Vallehermoso"],
    "La Gomera - Sur": ["Alajeró", "San Sebastián de La Gomera", "Valle Gran Rey"],
    "La Palma - Capitalina": ["Breña Alta", "Breña Baja", "Santa Cruz de La Palma",
                              "Villa de Mazo"],
    "La Palma - Noreste": ["Barlovento", "Puntallana", "San Andrés y Sauces"],
    "La Palma - Noroeste": ["Garafía", "Puntagorda", "Tijarafe"],
    "La Palma - Valle de Aridane": ["Fuencaliente de La Palma", "Los Llanos de Aridane",
                                    "El Paso", "Tazacorte"],
    "El Hierro - El Hierro": ["Frontera", "Valverde", "El Pinar de El Hierro"],
}
EXC_GEO = {
    38901: "El Pinar de El Hierro",
    35031: "Valsequillo de Gran Canaria",
    35023: "Santa María de Guía de Gran Canaria",
    38014: "Fuencaliente de La Palma",
    38052: "Vilaflor de Chasna",
    38023: "San Cristóbal de La Laguna",
}
